language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'
- '0.6'
env:
  global:
    secure: CkkZFe97bFjtJCvyNcmVFDOdmWdAH+jtm8mVy8vqKVjX8iyj2v8D8Gj5i5BFwJOJcSuXP2y1dkdov7lM16J6G1JDe/NEPb+uus6MaC67to/ptS5kdsE++72XCJfLR6SSXY+nNxmgq197qxU4nWOBWToAMmi3vmYBWHTCgW08i1Y=
